### ISSUE TITLE
New Releases don't get pushed properly

### ISSUE THREAD

**Issue by ifighftdragons** [ShadowOne333/A-Link-to-the-Past-Redux#16]
Whenever you update files on GitHub, you should push it as a new Release.

That way, people who have signed up for alerts on new releases, will be alerted when you've updated it.

The only way I found out that you've just updated it right now, is because I was randomly looking at new releases on Romhacking.net

I think a lot of people are missing these new releases, unless you actually push them on here properly.

Looking at Releases right now, it says 10.2.2 was updated last month. But when you actually click on it, you can see that the files within were updated just a few hours ago.

**Comment by ShadowOne333** [comment]
Ah yes, this is my fault.
Instead of making a new release, I simply edit the existing one for v10.2 and add the new files, while updating the version number as well.

I forgot some people are keeping track on the repository, so making new releases should be the way to go from now on.
Thanks for the heads up!
