### ISSUE TITLE
Assembly without text corrections

### ISSUE THREAD

**Issue by Dima353** [ShadowOne333/A-Link-to-the-Past-Redux#4]
Can you please tell me how to build a version of the patch without text corrections to apply a patch of another language?

**Comment by ShadowOne333** [comment]
The repository right now does not compile a proper Redux ROM atm, I still have yet to figure out how to do the map changes through the compilation script because FastROM + Map changes glitches the ROM.

You'd have to wait until the repository's source code is advanced enough to make a proper ROM without the text changes, and even then, you would most likely have to redo the other language manually because of pointer changes between texts and other stuff. I doubt other languages could work out of the box with Redux.
