### ISSUE TITLE
improvement

### ISSUE THREAD

**Issue by DarkLegend1987** [ShadowOne333/A-Link-to-the-Past-Redux#6]
hi guys this project is amazing give snes zelda a better form of gameplay but were more
amazing is can port the 4 sword palace to snes to make the definitive zelda game  or add the spin blade attack to snes can be so cool

**Comment by ShadowOne333** [comment]
Porting the Four Swords Palace into SNES could probably be feasible, but with how limited placing objects and other things into Zelda 3 is due to the limitations of objects would make it quite a difficult task.

Hopefully sometime in the future, I'd certainly love to have it on the SNES, but until adding objects into rooms gets easier, it's unlikely it'll happen anytime soon.
