### ISSUE TITLE
Confusion with MSU-1 tracks

### ISSUE THREAD

**Issue by agaskins** [ShadowOne333/A-Link-to-the-Past-Redux#7]
I will say up front that I have no experience patching for MSU-1 hacks with included audio files. That said, I read the README and I understand how to arrange the files and such, but I have three points of confusion:

a) I've downloaded several aLttP MSU-1 music archives (metal, symphonic, FM synth variants, for example) and they all have 35 files instead of the 34 specified in the README. So I'm not sure I have the right files, but even if these are compatible I'm not sure if the tracks are in the right order since there is an extra one.

b) Each archive of MSU-1 tracks I download has a .msu file, and most of them are the same size as the one that comes with the FMV track archive linked to in the README. Do I just stick with the that msu file or replace it with the one from the archive I use for audio?

c) these archives with 35 tracks have a music track for 34. How do I deal with this when including the FMV file? This might be answered in response to A, but I figured it was worth clarifying now.

I'm sorry if this is obvious to many, or if I somehow missed this info somewhere on here or in the README, but I'd appreciate any clarity on this, or if someone could just point me in the right direction to the relevant info.

Thanks!

**Comment by ShadowOne333** [comment]
a) The 35th track (from what I know) is the one used for the audio of the introduction FMV. There's no harm in having it from what I know unless you patch the "Enable FMV" optional patch.

b) This point confirms the a) point. The MSU file should be around a couple hundred MB in size, so that one file is the FMV on its own, while the 35th track is the audio. Always use the MSU file with actual data if you intend on having the FMV play on a new file. If you don't care about the FMV, you can simply have the 0 bytes .msu file and remove track 35.

c) I don't quite understand this point. I hope whatever doubt you had with this one was clarified in one of the previous two.


Let me know if you have any other doubts!

**Comment by agaskins** [comment]
You have indeed made everything clear @ShadowOne333

I apologize for being confused on this.... somehow I thought the README had said the FMV should be file 34, not 35 (as it indeed clearly states). So most of this was just me having a/ r/ihadastroke moment, ha. That said, your reply did clear up any and all questions I had and I just watched the amazing FMV intro and am listening to symphonic music! Thank you so very much!

Feel free to close this issue; all is well!

**Comment by ShadowOne333** [comment]
Great you got it working, enjoy the hack! :)
