### ISSUE TITLE
Using Redux in combination with Zelda3 PC Port

### ISSUE THREAD

**Issue by user18081972** [ShadowOne333/A-Link-to-the-Past-Redux#9]
Is there a way to apply this ROM hack (ALttP Redux) to the new Zelda3 reverse engineered PC port? It has true widescreen support and other nice features.

(The Port itself: https://github.com/snesrev/zelda3)
(A 1-click GUI: https://github.com/ajohns6/Zelda-3-Launcher/)

**Comment by ShadowOne333** [comment]
This should more or less go over the PC port guys rather than me, as this is solely related to the SNES ROM, while they are working with C language for the port. 

From what I know they are already aware that many people desire Redux features into the PC port, but that'd require converting the whole Redux project from 65816 assembly into C language.

I suggest checking the Issues on the PC port repository for Redux stuff
